# Generated by Django 3.0.3 on 2020-04-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0006_auto_20200417_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(default='purchases', max_length=50)),
                ('date', models.DateField()),
                ('debit', models.PositiveIntegerField(default=0, help_text='Debited from a buyer: Buyer account is')),
                ('credit', models.PositiveIntegerField(help_text='Credited to a supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('debit', models.PositiveIntegerField(help_text='Debited from a buyer')),
                ('credit', models.PositiveIntegerField(default=0, help_text='Credited to a supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Company')),
            ],
        ),
    ]
