# Generated by Django 3.0.3 on 2020-04-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0008_auto_20200423_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebook',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchasebook',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchasebook',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='account',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='purchasesledger',
            name='particulars',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasesledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Supplier'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter the bill/invoice number', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebook',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Bill'),
            preserve_default=False,
        ),
    ]
