# Generated by Django 3.0.3 on 2020-04-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0009_auto_20200423_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='date',
        ),
    ]
