# Generated by Django 3.0.3 on 2020-04-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0012_auto_20200429_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
